WorkflowTesting/Sources/Internal/RenderExpectations.swift
WorkflowTesting/Sources/Internal/RenderTester+TestContext.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift

#15  introduces a new `RenderTester` API, along with an `ExpectedWorkflow` type with `assertions`. However, we had missed hooking this up. Adding `assertions` to `ExpectedWorkflow` type.

Hookup ExpectedWorkflow Assertions

---

WorkflowTesting/Sources/DeprecatedRenderExpectations.swift
WorkflowTesting/Sources/WorkflowRenderTester+Deprecated.swift

Make sure deprecated RenderTester expectation failures get attributed to the correct file/line.
Also, add missing deprecation marking on `WorkflowRenderTester.assert(state:)`

Add missing file/line to deprecated render expectations

---

WorkflowReactiveSwift/Testing/WorkerTesting+Deprecated.swift
WorkflowReactiveSwift/Tests/WorkerTests.swift
WorkflowTesting/Tests/WorkflowRenderTesterDeprecatedTests.swift
WorkflowUI/Tests/ContainerViewControllerTests.swift

Mostly, mark tests that use deprecated things as themselves deprecated. Also migrated one missing thing thing off of deprecated methods.

Get rid of warnings across the project

---

WorkflowReactiveSwift/TestingTests/TestingTests.swift
WorkflowTesting/Sources/Internal/RenderTester+TestContext.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift

`Void` only has a single value, so it’s reasonable/possible for `RenderTester`’s `RenderContext` to return a rendering for unexpected workflows that render `Void`.
Notably, this allows us to fail but continue testing when we encounter an unexpected `Worker` (and thus we can bring back `test_worker_unexpected`).

Recover from unexpected void-rendering workflows in RenderTester

---

WorkflowReactiveSwift/Tests/WorkerTests.swift
WorkflowRxSwift/Tests/WorkerTests.swift

Fixing @bencochran 's feedback on `WorkflowRxSwiftTests` for `WorkflowReactiveSwiftTests`: https://github.com/square/workflow-swift/pull/27#discussion_r449185026

Do not use @testable import Workflow in WorkflowReactiveSwiftTests

---

WorkflowTesting/Sources/Internal/RenderTester+TestContext.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift

`WorkflowTesting` was not accurately testing the scenario where we render multiple child Workflows with the same key.
Fixing it here.

Fix WorkflowTesting with Multiple Child Workflows

---

.github/workflows/swift.yaml
WorkflowReactiveSwift/Tests/SignalProducerTests.swift
WorkflowReactiveSwift/Tests/WorkerTests.swift

Created a circular `.podspec` dependency.

Rm WorkflowReactiveSwiftTesting dependency from WorkflowReactiveSwiftTests

---

Samples/SampleApp/Sources/DemoWorkflow.swift
WorkflowReactiveSwift/Sources/SignalWorker.swift
WorkflowUI/Tests/ContainerViewControllerTests.swift

The `key` in `asWorker` is not carried over to the key used to render the `Workflows`. Since, the `Workers` are now keyed based on type + key, this may cause a run-time exception. Marking `asWorker` as `unavailable` minimize this risk.

Mark asWorker unavailable

---

Gemfile
Gemfile.lock
RELEASING.md
WorkflowUI.podspec
version.rb

Bumping up `cocoapods-trunk`, to make use of the `--synchronous` option in `cocoapods-trunk = 1.5.0`.

Fixing Release Instructions

---

.github/workflows/swift.yaml
WorkflowReactiveSwift.podspec
WorkflowReactiveSwift/Sources/Worker.swift
WorkflowRxSwift/Sources/Worker.swift

@AquaGeek pointed this out during migration, `Rendering` for a `Worker` should always be `Void`.

Constrain Worker Rendering type to Void

---

.github/workflows/swift.yaml
WorkflowReactiveSwift/Testing/SignalProducerWorkflowTesting.swift
WorkflowReactiveSwift/TestingTests/SignalProducerTests.swift
WorkflowRxSwift/Testing/ObservableTesting.swift
WorkflowRxSwift/TestingTests/ObservableTests.swift

During migration @AquaGeek found that these were un-testable since `SignalProducerWorkflow` is `internal`. This unblocks this.
@AquaGeek , @bencochran : Any better ideas on how we can accomplish this?

Enable testing of SignalProducer/Signal/Observable used in Workflows

---

WorkflowTesting/Sources/WorkflowActionTester.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift

This PR corrects a minor typo in a `WorkflowActionTester` deprecation warning. Additionally, it updates `RenderTester` documentation to track recent changes to testing APIs.
(NA)

[Gardening] Polish documentation

---

Workflow/Sources/RenderContext.swift

We accidentally forgot to deprecate this when moving to the `rendered(in:)` API. Fixes #52.
(Of note: there look to be a handful of uses of this across Square code, so this’ll cause a migration)

Deprecate `RenderContext.render(workflow:)`

---

Workflow/Sources/RenderContext.swift

Introduce  'makeOutputSink' convenience on 'RenderContext'

---

Workflow/Sources/AnyWorkflowConvertible.swift
Workflow/Tests/AnyWorkflowTests.swift

Convenience onOutput transformer for AnyWorkflow

---

MigrationGuide_v1.0.md
Workflow/Sources/AnyWorkflowConvertible.swift

This was replaced by `rendered(in:key:)`.

Remove deprecated rendered(with:key:)

---

MigrationGuide_v1.0.md
Workflow/Sources/RenderContext.swift

This method was accidentally marked `public` a while back.
I think we have 3 usages of it (internally) that we'll need to migrate.

Make RenderContext.render(workflow:key:outputMap:) internal

---

Samples/Tutorial/Tutorial1.md
Tooling/Templates/Workflow (Verbose).xctemplate/___FILEBASENAME___Workflow.swift

`Tooling/Templates/Workflow (Verbose).xctemplate/___FILEBASENAME___Workflow.swift` doesn't build out of the box: it references but does not include `WorkflowReactiveSwift`
Also: updated path to TutorialBase in the Tutorial1 docs.

Add WorkflowReactiveSwift to base Workflow Xcode template

---

.github/workflows/swift.yaml

Uses a device version that's available in CI. Fixes [build](https://github.com/square/workflow-swift/pull/86/checks?check_run_id=1393763821).

Updating device for tests

---

Package.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/List/TodoListScreen.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/List/TodoListWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/TodoWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/TodoWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/RootWorkflowTests.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/TodoEditWorkflowTests.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/TodoListWorkflowTests.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/TodoWorkflowTests.swift
WorkflowRxSwift.podspec

Pinned SwiftFormat and ran it on the entire project.

Pin SwiftFormat to 0.44.14

---

WorkflowTesting/Sources/Internal/AppliedAction.swift
WorkflowTesting/Sources/RenderTesterResult.swift
WorkflowTesting/Sources/WorkflowActionTester.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift
WorkflowTesting/Tests/WorkflowActionTesterTests.swift
WorkflowTesting/Tests/WorkflowRenderTesterTests.swift

This PR makes allowances for throwing assertions in `ActionTester.verify` and `RenderTester.render`. These changes are meant to support tests which take advantage of XCTest's expanding API for test cases which throw.
Example of the impact of this change:
**Old:**
```swift
func test_saveEvents() {
Action
.tester(withState: state)
.send(action: .beginSave)
.verifyOutput { output in
XCTAssertEqual(output.events[0], .startedSave)
}
}
```
**New:**
```swift
func test_saveEvents() throws {
try Action
.tester(withState: state)
.send(action: .beginSave)
.verifyOutput { output in
let first = try XCTUnwrap(output.events.first)
XCTAssertEqual(first, .startedSave)
}
}
```

[WorkflowTests] Support assertions which throw

---

Workflow/Sources/SubtreeManager.swift
Workflow/Tests/ConcurrencyTests.swift

Queued Events are events sent to the `Sink` synchronously while `Screen`s are being updated. We `queue` them up and are applied after the `Screen` update operation.
Our existing implementation of `Queued` events handling has a few issues:
* Each `Workflow` node can handle only one event, if another event is sent, we `fatalError` with a `Action sent to pipe while in the pending state.` message.
* If multiple `Workflow` nodes have events queued, only one of them will be handled, the rest are silently dropped.
* Due to a bug in `enabling` and handling `EventPipes` while handling `queued` events, the Workflow tree can get into an inconsistent state and sometimes leads to a crash.
To solve this issue, in this PR, we are not queueing events in the `SubtreeManager`, instead we schedule the event …

Handling Queued Events

---

Workflow/Sources/AnyWorkflowConvertible.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift
WorkflowTesting/Tests/WorkflowRenderTesterTests.swift

This PR adds a helper method to `AnyWorkflowConvertible` to ignore outputs.
I'm not sure if this is testable, but happy to add tests if someone has an idea how!

Add helper method to ignore output

---

WorkflowRxSwift.podspec

Internally, Square has switched to `RxSwift 5.1.1`. This change reflects that update.

Bump RxSwift to 5.1

---

WorkflowRxSwift.podspec
WorkflowRxSwift/Sources/ObservableWorkflow.swift

Bump RxSwift to 6.2

---

Samples/Tutorial/Tutorial4.md
Samples/Tutorial/Tutorial5.md

This is just a minor fix to some documentation in the Tutorials.
While going through the tutorials, I noticed that Tutorial 4 didn't link to Tutorial 5 like the others do which was a little jarring. Definitely open to rewording the snippet. I also noticed some minor formatting issues in Tutorial 5.

Tutorial Formatting Fixes

---

Workflow/Sources/AnyWorkflowConvertible.swift

Bumping into this while pushing to cocoapods. Must be a 13.1 thing.

Fix redundant conformance warning

---

WorkflowUI/Sources/Container/ContainerViewController.swift
WorkflowUI/Sources/ViewControllerDescription/DescribedViewController.swift
WorkflowUI/Tests/DescribedViewControllerTests.swift

- Adds additional view controller property forwarding to contained view controllers in `ContainerViewController` and `DescribedViewController`
- Fixes a missing preferred content size update and avoids updating the preferred content size in a few cases where it did not previously
- Adds contained child view controllers as children in the initializer for these containers. This allows consumers to inspect properties of the view controller before the view has loaded and get appropriate values—previously this would return a default value until the view was loaded even though the information was available.

Fix bugs related to view controller containment

---

WorkflowUI/Sources/ViewControllerDescription/DescribedViewController.swift
WorkflowUI/Tests/DescribedViewControllerTests.swift

Fixes an issue where the child of a `DescribedViewController` wasn't removed even when the `currentViewController` was replaced. This issue was introduced in https://github.com/square/workflow-swift/pull/108 - we started setting up the parent-child relationship in the init, but only remove the child if our view is loaded. In the case where an update happens before the view is loaded, that initial child is never removed.
The left-behind relationship and view was causing issues where (correct) assumptions about the view and view controller hierarchy were invalid, causing this crash: https://square.slack.com/archives/CTJ4UNLHF/p1641510705024100
Thanks @tyten and @kyleve for helping debug!

Always remove child view controller from DescribedViewController

---

WorkflowCombine/Sources/PublisherWorkflow.swift

https://github.com/square/workflow-swift/issues/118

Fixed issue 118 PublisherWorkflow forcing subscriptions to run on main run loop

---

WorkflowUI/Sources/ViewControllerDescription/ViewControllerDescription.swift
WorkflowUI/Tests/ViewControllerDescriptionTests.swift

Currently the view controller passed into ViewControllerDescription at build time must be of a concrete type. `canUpdate(viewController:)` does a type equality check, which fails if the view controller's concrete type does not match the inferred type at initialization. In this case, the program will crash.
This change allows for type conformance, which means that subclasses or abstract view controller types can be used at initialization.
- N/A 
- N/A 
- N/A

Allow type conformance in ViewControllerDescription

---

WorkflowRxSwift.podspec

Revert RxSwift Bump to 6.5.0

---

WorkflowConcurrency/Sources/TaskWorkflow.swift
WorkflowConcurrency/Tests/TaskTests.swift

Removing the closure to a Task and just passing in the Task to the TaskWorkflow fixes the compiler crash.

Fixed Swift 5.6+ compiler crash in TaskWorkflow

---

Development.podspec
Package.swift
WorkflowConcurrency.podspec
WorkflowConcurrency/Sources/Logger.swift
WorkflowConcurrency/Sources/TaskWorkflow.swift
WorkflowConcurrency/Sources/Worker.swift
WorkflowConcurrency/Tests/TaskTests.swift
WorkflowConcurrency/Tests/WorkerTests.swift

Creating a PR for Soo's work on adding concurrency support for async workers.
This adds a WorkflowConcurrency module that defines a `Worker` protocol that can run an `async` function and allows `Task`'s to be run as a workflow.

Workflow concurrency support for workers

---

WorkflowUI/Sources/Screen/ScreenViewController.swift
WorkflowUI/Sources/ViewControllerDescription/ViewControllerDescription.swift
WorkflowUI/Tests/ViewControllerDescriptionTests.swift

This change allows disabling the initial update that occurs within `buildViewController`, which is not desired for container view controllers in many cases: When your container view controller (eg, nav stack, tab bar) creates its `DescribedViewControllers` in init, they are already updated with their content. Disabling the update during `buildViewController` allows us to skip duplicate updates to them that end up occurring immediately after.

Introduce performInitialUpdate to allow disabling updates during view controller building

---

Workflow/Sources/SubtreeManager.swift
Workflow/Sources/WorkflowHost.swift
Workflow/Sources/WorkflowLogger.swift
Workflow/Sources/WorkflowNode.swift
Workflow/Tests/PerformanceTests.swift
WorkflowReactiveSwift/Sources/Logger.swift
WorkflowRxSwift/Sources/Logger.swift

- during some recent investigations into rendering performance, we found that leaving the runtime os logging enabled (the current implicit behavior) had a noticeable adverse effect.
- logging is now opt-in, and disabled by default
- added additional configuration options to control which categories of runtime data are logged
- added synthetic performance tests to gut check execution time changes under various logging configurations
example XCTest run after disabling logging:

[performance]: disable logging by default & add logging configuration

---

Workflow/Sources/WorkflowLogger.swift

- clean up internal logging utility method

[gardening]: logging utility method cleanup

---

WorkflowUI.podspec
WorkflowUI/Sources/Container/ContainerViewController.swift
WorkflowUI/Sources/Screen/Screen.swift
WorkflowUI/Sources/ViewControllerDescription/DescribedViewController.swift
WorkflowUI/Sources/ViewControllerDescription/UIViewController+Extensions.swift
WorkflowUI/Sources/ViewControllerDescription/ViewControllerDescription.swift
WorkflowUI/Tests/ContainerViewControllerTests.swift
WorkflowUI/Tests/UIViewControllerExtensionTests.swift
WorkflowUI/Tests/ViewControllerDescriptionTests.swift
WorkflowUI/Tests/XCTestCase+Extensions.swift

This change makes it easier to avoid using `DescribedViewController`, which adds a (largely needless) layer to view controller hierarchies. I'll leave comments inline on relevant additions with comments.
For Square folks, I recommend seeing how this is used in context in https://github.com/squareup/market/pull/4559.

Updates to make it easier to avoid using `DescribedViewController`, allowing flattening of VC hierarchies.

---

Samples/AsyncWorker/AsyncWorker/SceneDelegate.swift
Samples/SampleApp/Sources/AppDelegate.swift
Samples/SplitScreenContainer/DemoApp/AppDelegate.swift
Samples/TicTacToe/Sources/AppDelegate.swift
Samples/Tutorial/AppHost/Sources/AppDelegate.swift
Samples/Tutorial/Frameworks/Tutorial1Complete/Sources/TutorialHostingViewController.swift
Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/TutorialHostingViewController.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/TutorialHostingViewController.swift
Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/TutorialHostingViewController.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/TutorialHostingViewController.swift
Samples/Tutorial/Frameworks/TutorialBase/Sources/TutorialHostingViewController.swift
Samples/Tutorial/README.md
Samples/Tutorial/Tutorial.xcodeproj/xcshareddata/xcschemes/Tutorial.xcscheme
Samples/Tutorial/Tutorial1.md
Samples/Tutorial/Tutorial2.md
Samples/Tutorial/Tutorial5.md
Samples/WorkflowCombineSampleApp/WorkflowCombineSampleApp/AppDelegate.swift
WorkflowUI/Sources/Hosting/WorkflowHostingController.swift
WorkflowUI/Sources/Screen/ViewEnvironment/ViewEnvironment.swift
WorkflowUI/Tests/DescribedViewControllerTests.swift
WorkflowUI/Tests/WorkflowHostingControllerTests.swift

This renames `ContainerViewController` to `WorkflowHostingController` to (a) be a less generic name (basically _any_ parent view controller is a "container") / explain what the VC is containing/hosting, and (b) aligns us more closely with SwiftUI's `UIHostingController` naming.
I've left the old name as a deprecated name – we can remove it in a 2.0 (assuming we follow proper semver?) in perhaps a couple months. I'll migrate POS / etc.

Rename ContainerViewController to WorkflowHostingController

---

Package.swift
WorkflowReactiveSwift/Testing/SignalProducerWorkflowTesting.swift
WorkflowReactiveSwift/TestingTests/SignalProducerTests.swift
WorkflowTesting/Sources/Internal/RenderTester+TestContext.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift

- some behaviors in the testing facilities aren't particularly clear and may be confusing
- add clarification in comments that only a single output should be expected during a render test, and remove example code in comments suggesting this is possible.
- add a new SignalProducerWorkflow testing method for use when no output is expected
- add recovery suggestion to the diagnostic message produced when an unexpected child workflow is rendered in a test

[chore]: clarify some testing behaviors

---

Workflow/Sources/StateMutationSink.swift
Workflow/Tests/StateMutationSinkTests.swift

From @dhavalshreyas's [proposal in Notion](https://www.notion.so/sellermobile/Workflow-Boilerplate-Reduction-be0ccb80c5a044c0b564d09ddd1ff63f#62d55b4121aa428095b7370ebce43c9e) (with slightly updated examples):
`Sink`s are used to process `Action`s, either from `SideEffect`s or from user-interaction events.
We currently have `makeSink` to process any `Action` and `makeOutputSink`, which provides a `Sink` that sends the `Output`.
The proposal here is to introduce `makeStateMutationSink`, which would provide a `Sink` that automatically mutates `State` without an intermediate `Action`.
**Before:**
```swift
struct MyWorkflow: Workflow {
enum Action: WorkflowAction {
typealias WorkflowType = MyWorkflow
case updateTapCount(Int)
func apply(toState state: inout Int) -> MyWorkflow.Output? {
switch …
```

Add StateMutationSink

---

WorkflowCombineTesting.podspec
WorkflowConcurrencyTesting.podspec
WorkflowReactiveSwiftTesting.podspec
WorkflowUI.podspec

- WorkflowUI podspec failed validation, so publishing 1.3.0 failed
- fix the underlying issue, by allowing test specs which use an app host to unset the `APPLICATION_EXTENSION_API_ONLY` config

[fix]: modify testing podspecs to address validation errors

---

.github/workflows/swift.yaml
Package.swift
Workflow.podspec
Workflow/Sources/RenderContext.swift
Workflow/Sources/WorkflowHost.swift
WorkflowReactiveSwift/Sources/QueueScheduler+Workflow.swift

Re-do of https://github.com/square/workflow-swift/pull/173 within the repo (deleted my fork too soon)
I want to wean the core off of ReactiveSwift. 
This PR does two things:
* Update Package.swift
* Reorganize the file
* Expose the RxSwift flavors
* Update ReactiveSwift to be consistent with the Podspec
* Remove `import ReactiveSwift` for anything that didn't really need it

Start sectioning off ReactiveSwift

---

RELEASING.md

- adds some additional guidance/instruction to the releasing instructions doc

[docs]: update releasing docs

---

Workflow/Sources/AnyWorkflow.swift

- to support the `mapRendering` & `mapOutput` API, `AnyWorkflow` internally stores these transformations in a storage type
- the existing method implementations would retain the existing storage object unnecessarily, when only the existing transform need be retained
- removed the unnecessary captures of the full internal storage object when mapping outputs/renderings

[fix]: minor storage lifetime optimization

---

Workflow/Sources/Workflow.swift

- Workflow doesn't yet expose primary associated types, which makes some forms of type-erasure less useful or impossible
- adds `Rendering` and `Output` as the primary associated types of the `Workflow` protocol

[feat]: add primary associated types to `Workflow` protocol

---

Workflow/Sources/AnyWorkflowConvertible.swift
Workflow/Sources/WorkflowAction.swift
WorkflowCombine/Sources/Worker.swift
WorkflowConcurrency/Sources/Worker.swift
WorkflowReactiveSwift/Sources/Worker.swift
WorkflowRxSwift/Sources/Worker.swift

since we've bumped to swift 5.7, let's add primary associated types in some more places
- adds `<Rendering, Output>` PAT to `AnyWorkflowConvertible`
- adds `<WorkflowType>` PAT to `WorkflowAction`
- adds `<Output>` to the various definitions of `Worker`

[feat]: add primary associated types to more protocols

---

Workflow/Sources/SubtreeManager.swift
Workflow/Tests/SubtreeManagerTests.swift

previously we would allow a strong reference to the internal `ReusableSink` to be captured by the `Sink` types that are vended to clients. this meant that events sent into such 'external' sinks would still propagate through the event handling machinery a bit before realizing that the backing workflow node to which they were destined was no longer around. by using weak references we can prevent extending the life of the internal sinks (and underlying EventPipe) unnecessarily in such cases.
- make `ReusableSink` captures `weak` when vending to the 'outside world'
- update various access control values to facilitate testing this behavior

[fix]: use weak reference to internal sinks when vending to clients

---

Workflow/Sources/SubtreeManager.swift
Workflow/Sources/WorkflowNode.swift
Workflow/Tests/SubtreeManagerTests.swift

since we now have access to primary associated types, there are a couple places internally where it likely makes sense to leverage the language's 'existential' boxing facilities over our own. to start, we'll update a couple places that pass an `AnyWorkflowAction<T>` that can now be replaced with `any WorkflowAction<T>`.
additional comments inline.

[chore]: refactor some internal actions to use existential any

---

RELEASING.md
WorkflowConcurrency.podspec
WorkflowConcurrencyTesting.podspec
version.rb

(major) version bump and minor cleanup
- remove WORKFLOW_CONCURRENCY_VERSION & related code/docs
- bump WORKFLOW_VERSION to 2.2.0 (to align with what the concurrency version would have been)

[release]: bump version to 2.2.0 & remove separate concurrency version

---

WorkflowUI/Sources/Screen/AnyScreen/AnyScreen.swift

When using observation APIs from https://github.com/square/workflow-swift/pull/168 encountering an instance of `AnyScreen` leaves you with no options for retrieving the underlying type and doing something with it.
```swift
func workflowWillRender<WorkflowType: Workflow>(
_ workflow: WorkflowType,
state: WorkflowType.State,
session: WorkflowSession
) -> ((WorkflowType.Rendering) -> Void)? {
return { (rendering: WorkflowType.Rendering) -> Void in
guard let screen = rendering as? Screen else {
return
}
if screen is AnyScreen {
// ?? Can't do anything here since we cannot access `.wrappedScreen`
}
}
}        
```
This can also come up in `ScreenViewController.update(screen:environment:)` when using Screen types that wrap other screen values, such as …

Expose AnyScreen.wrappedScreen for inspection

---

WorkflowUI/Sources/Screen/AdaptedEnvironmentScreen.swift
WorkflowUI/Tests/AdaptedEnvironmentScreenTests.swift

This mirrors the API allowed on `Elements` in blueprint, to ease `ViewEnvironment` modification. For example, you might do something like this:
```swift
func render(...) -> Rendering {
MarketSelectSheetScreen( ... construct your select actions ...)
.adaptedEnvironment(keyPath: \.isContentAreaEnabled, value: state.isSaving == false)
}
```

Introduce AdaptedEnvironmentScreen, for modifying the ViewEnvironment when creating screens

---

Workflow/Sources/WorkflowAction.swift
Workflow/Tests/AnyWorkflowActionTests.swift
WorkflowUI/Sources/Screen/AnyScreen/AnyScreen.swift

this change adds introspection capabilities for what i believe is the final type-eraser that lacks them – AnyWorkflowAction. changes include:
- adds a public `base` property on `AnyWorkflowAction` to expose the underlying action as an `Any` value
- adds an internal utility type, `ClosureAction`, for closure-based `AnyWorkflowAction`s. the intent is to provide the possibility of improved telemetry information when logging such actions.
- adds a new public property `isClosureBased` on `AnyWorkflowAction` to differentiate instances that forward to an underlying wrapped action vs those whose implementations are defined by a closure.

[task]: attempt to improve debugging info for AnyWorkflowAction

---

WorkflowUI/Sources/Screen/AdaptedEnvironmentScreen.swift

Based on the work done in https://github.com/square/workflow-swift/pull/106, so that way you can do an adaptation before, eg you map something to a `Screen`.

Conditionally conform AdaptedEnvironmentScreen to Screen, based on its content

---

WorkflowConcurrency/Sources/Worker.swift
WorkflowConcurrency/Tests/WorkerTests.swift

Changed WorkerWorkflow to use it’s state as the key for the runSideEffect call so that if the state changes the worker is re-run.
Updated unit tests to test for this issue of the side effect not running.
Added unit tests for testing that updating the key in the render call causes the worker to run.

Fixed runSideEffect key in WorkflowConcurrency Worker

---

Samples/WorkflowCombineSampleApp/WorkflowCombineSampleApp/DemoWorker.swift
Samples/WorkflowCombineSampleApp/WorkflowCombineSampleApp/DemoWorkflow.swift
WorkflowCombine/Sources/Publisher+Extensions.swift
WorkflowCombine/Sources/PublisherWorkflow.swift

Without this API consuming a `Publisher` inside a workflow is only possible by either rendering it directly via `.render(in:)` or by first calling `mapOutput`:
```swift
somePublisher
.mapOutput { $0 } // workaround for not being able to call `asAnyWorkflow()`
.onOutput { state, output in
// ...
}.rendered(in: context)
```

Expose Publisher.asAnyWorkflow as public API

---

Workflow/Sources/WorkflowNode.swift
Workflow/Tests/WorkflowObserverTests.swift

- under some circumstances, the action application observation codepath could trigger runtime memory exclusivity exceptions
- added a test case that reproduces the issue with the existing API
- removed an unneeded `inout` parameter to resolve the problem

[fix]: resolve memory exclusivity violations in some WorkflowObserver paths

---

Package.swift
Samples/TicTacToe/Sources/Authentication/LoginScreen.swift
Samples/Tutorial/Podfile
ViewEnvironmentUI/Tests/ViewEnvironmentObservingTests.swift
WorkflowUI.podspec
WorkflowUI/Sources/Hosting/WorkflowHostingController.swift
WorkflowUI/Sources/ModuleExports.swift
WorkflowUI/Sources/Screen/ScreenViewController.swift
WorkflowUI/Sources/ViewControllerDescription/ViewControllerDescription.swift
WorkflowUI/Tests/DescribedViewControllerTests.swift
WorkflowUI/Tests/UIViewControllerExtensionTests.swift
WorkflowUI/Tests/ViewControllerDescriptionTests.swift
WorkflowUI/Tests/WorkflowHostingControllerTests.swift

> **Note**: This PR is targeting the [`feature/viewenvironmentui`](https://github.com/square/workflow-swift/tree/feature/viewenvironmentui) branch and depends on #205.
This PR adds deep integration of `ViewEnvironmentUI` to `WorkflowUI`. This deep integration makes working with contexts that need to bridge between both systems _much_ easier. For example, applications that have not fully adopted Workflow but utilize the `ViewEnvironment` for theme propagation via `ViewEnvironmentUI` (as is true in Square's ios-register codebase).
This PR is part of the larger effort to add support for automatic `ViewEnvironment` bridging between `UIKit` propagation and `WorkflowUI` propagation within `WorkflowUI`.
See [the associated proposal](https://www.notion.so/marketdesignsystem/Proposal-WorkflowUI-Vie …

[feat]: Add support for automatic ViewEnvironment bridging in WorkflowUI

---

.github/CODEOWNERS

update codeownership so that the `foundation-ios` team is still added as a reviewer on WorkflowUI changes

[chore]: update codeowners

---

WorkflowUI/Sources/Hosting/WorkflowHostingController.swift

> **Note**: This PR is targeting the [`feature/viewenvironmentui`](https://github.com/square/workflow-swift/tree/feature/viewenvironmentui) branch and depends on #218.
This PR is part of the larger effort to add support for automatic `ViewEnvironment` bridging between `UIKit` propagation and `WorkflowUI` propagation within `WorkflowUI`.
See [the associated proposal](https://www.notion.so/marketdesignsystem/Proposal-WorkflowUI-ViewEnvironment-Propagation-in-UIKit-0aec81d8c40545baa2ed7bacd938a6b7#879e5ce5c3f948d59174c9d18a7e6441) for more information.
While this change may seem unrelated to the view environment bridging work, it was added to this feature branch since it allows replacement of `DescribedViewController` usages with `WorkflowHostingController`s without loading the view earlier …

[fix]: make WorkflowHostingController background color clear

---

ViewEnvironmentUI/Sources/ViewEnvironmentPropagating.swift
WorkflowUI/Sources/Hosting/WorkflowHostingController.swift
WorkflowUI/Tests/WorkflowHostingControllerTests.swift

When a `WorkflowHostingController` is added to a `UIViewController` hierarchy, we need to ensure that we re-render the `Screen` using an updated `ViewEnvironment`, since the environment from the ancestor path above that `WorkflowHostingController` could contain customizations that are not present in the `WorkflowHostingController` itself.
Currently, it is expected that consumers would call `setNeedsEnvironmentUpdate()` when adding a `WorkflowHostingController` as a child, but this is fragile and hard to enforce/validate, especially in legacy code.
Omitting this `setNeedsEnvironmentUpdate()` can cause issues where content would be rendered on screen using invalid `ViewEnvironment` values on the first rendering. On a later environment update, we'd likely see this environment reflect the …

[fix]: update WorkflowHostingController on layout if ancestor hierarchy has changed

---

WorkflowCombine/Testing/PublisherTesting.swift
WorkflowCombine/TestingTests/PublisherTests.swift

- the `WorkflowCombine` `RenderTester` extensions didn't allow `nil` output
- add a new method to support `nil` output and match the naming convention of analogous methods
- deprecate old method
- update tests
addresses https://github.com/square/workflow-swift/issues/235

[fix]: support nil output in RenderTester Publisher extension

---

WorkflowCombine/TestingTests/TestingTests.swift
WorkflowConcurrency/TestingTests/TestingTests.swift
WorkflowReactiveSwift/TestingTests/TestingTests.swift
WorkflowTesting/Sources/Internal/RenderTester+TestContext.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift

when the `RenderTester`'s `RenderContext` cannot produce a value for the expected rendering type, it must abort program execution. the informative error message that is used to populate a test failure description isn't as easily discoverable in Xcode's diagnostic overlay in this case.
update the messaging in these circumstances
now looks like:

[fix]: improve fatal error diagnostic message in RenderTester

---

Workflow/Sources/RenderContext.swift

the `makeSink(...)` method of the concrete `RenderContext` implementation did not include the same validation assertion that all other methods of the type have. this could lead to issues where a context was retained outside of a `render(...)` method and if it was used to make a sink outside that method, we would not detect that unexpected state.
- adds a `assertStillValid` check to the `makeSink` method
- adds doc comments for the method
note: personally i think we should aim to go a bit further and make the validation assertion a precondition as well as destroy the reference to the internal context when the externally-accessible context is invalidated. but that sort of change likely requires gathering some data about places that might currently break if we were to fail more …

[fix]: add render context validation check to makeSink

---

WorkflowTesting/Sources/RenderTesterResult.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift
WorkflowTesting/Tests/WorkflowRenderTesterTests.swift

- Before: To perform exhaustive state assertions with a RenderTester you have to manually keep track of the initial state.
- After: Added RenderTesterResult/assertState which makes it easy to perform exhaustive state assertions by mutating the initial state

Exhaustive RenderTester state assertion

---

WorkflowReactiveSwift/Testing/SignalProducerWorkflowTesting.swift
WorkflowReactiveSwift/TestingTests/SignalProducerTests.swift
WorkflowRxSwift/Testing/ObservableTesting.swift
WorkflowRxSwift/TestingTests/ObservableTests.swift

due to generic type inference behavior, certain `RenderTester` utilities made it impossible (or at least convoluted) to test underlying Workflows that had outputs of Optional type.
- audited existing `RenderTester` extensions
- added optional type parameters to methods that lacked a way to specify the expected generic types directly
~- [ ] UI Tests~ n/a
~- [ ] Snapshot Tests (iOS only)~ n/a
~- [ ] I have made corresponding changes to the documentation~ n/a

[fix]: address some RenderTester limitations with optionals

---

WorkflowUI/Sources/Hosting/WorkflowHostingController.swift

Adds `WorkflowHostingController.screen` to allow consumers to inspect the latest screen that is currently being displayed by the host

Expose 'screen' on WorkflowHostingController

---

Package.swift
WorkflowReactiveSwift.podspec
WorkflowRxSwift.podspec
WorkflowRxSwiftTesting.podspec

This bumps RxSwift to v6.6, which now declares extension safety.
I then updated the Podspec to declare explicit extension safety.
I apparently had missed ReactiveSwift in [the first PR](https://github.com/square/workflow-swift/pull/171).
All tasks are n/a

RxSwift 6.6

---

Package.swift

This change implements a convenience method in `Package.swift` to reduce the boilerplate in the package definition. Inspired by [Krzysztof Zabłocki - The Project Template](https://youtu.be/9KOnO77msU8?t=263)

Add convenience method for library definitions to reduce boilerplate

---

Development.podspec
WorkflowSwiftUIExperimental.podspec
WorkflowSwiftUIExperimental/README.md
WorkflowSwiftUIExperimental/Sources/EnvironmentValues+ViewEnvironment.swift
WorkflowSwiftUIExperimental/Sources/ObservableValue+Binding.swift
WorkflowSwiftUIExperimental/Sources/ObservableValue.swift
WorkflowSwiftUIExperimental/Sources/SwiftUIScreen.swift
WorkflowSwiftUIExperimental/Sources/WithModel.swift

This adds a `WorkflowSwiftUIExperimental` module containing a set of core reusable types for implementing Workflow screens using SwiftUI.
These types are experimental and not recommended for use in production, but have reoccurred unchanged in a series prototypes over the last year. They were previously copy-pasted in each prototype, and more recently lived in a [WorkflowSwiftUIExperimental repo](https://github.com/squareup/WorkflowSwiftUIExperimental).
Moving them to this repository will allow future prototypes to be written as branches of Workflow, which may include both new sample code and changes to the WorkflowSwiftUIExperimental and Workflow types themselves.
For now this module will be [disallowed as a dependency in Register](https://github.com/squareup/ios-register/pull/91039/commit …

Add WorkflowSwiftUIExperimental 

---

RELEASING.md

WorkflowSwiftUIExperimental is a new pod that should also be pushed to trunk when releasing. This updated the releasing instructions accordingly.

[chore]: add WorkflowSwiftUIExperimental to list of pods to push

---

.hooks/pre-commit
.swiftformat

the current pre-commit hook builds & runs swiftformat on every lint-able file, which can take a relatively long time if many changes have been made
- updates commit hook script to make one call to swiftformat with all the files to lint
- adds a `swiftversion` config specifying 5.7 as the language version the linter will use when running

[gardening]: batch swiftlint calls for all modified files

---

WorkflowUI/Sources/Screen/AdaptedEnvironmentScreen.swift

Oops, my bad on this one... These should be public.

Ensure all adapted environment methods are public

---

WorkflowSwiftUIExperimental.podspec
version.rb

the current experimental swift ui target is versioned independently from the other pods. this change relaxes the version requirements for its dependencies to allow any minor or patch changes to be made without this podspec having to be changed.

[chore]: relax swiftui experimental dependency constraints & bump version

---

ViewEnvironment/Sources/EnvironmentValues+ViewEnvironment.swift

Moving this environment value key to `ViewEnvironment` means that modules that aren't dependent on WorkflowUI (like MarketSwiftUI) are able to access `ViewEnvironment` keys on the SwiftUI `EnvironmentValues`. Market will use this key to access the `MarketContext` on the `ViewEnvironment` which is bridged by either our Market SwiftUI Hosting Controller or the standard WorkflowUI SwiftUI Screen depending on context rather than having to manually bridge the `MarketContext` in addition to the `ViewEnvironment`, and have the potential for the `MarketContext`s in both environments to get out of sync.
The integration in Market can be found here: https://github.com/squareup/market/pull/7763
[UI-5335](https://block.atlassian.net/browse/UI-5335)

[chore]: move ViewEnvironment's EnvironmentValues key to the ViewEnvironment module

---

WorkflowTesting/Sources/Internal/RenderExpectations.swift
WorkflowTesting/Sources/Internal/RenderTester+TestContext.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift

Nested type ExpectedSideEffect was using the same name for the workflow generic type as the outer type RenderTester.  This created a shadowed type name warning.
Removing the generic type got rid of the warning

Removed unnecessary nested generic type

---

Development.podspec
WorkflowSwiftUIExperimental.podspec
WorkflowSwiftUIExperimental/Sources/SwiftUIScreen.swift
WorkflowSwiftUIExperimental/Tests/SwiftUIScreenTests.swift

Market's Modal framework relies on `preferredContentSize` to size modals during presentation.
Without any changes, view controllers that back `SwiftUIScreen`s never had their `preferredContentSize` updated. 
`SwiftUIScreen` is backed by a `UIHostingController` subclass. In iOS 16 and above, a new `sizingOption` parameter was added that allows a consumer to specify the `.preferredContentSize` option which will cause the view controller to update the `preferredContentSize` as it changes over time. Before iOS 16, you have to do this manually.
One thing that's surprising is that with the `sizingOption` support for `preferredContentSize`, the `preferredContentSize` does not appear to be updated after the first layout. Also, the `UIHostingController`'s `view` is does not appear to have …

[feat]: add support for sizingOptions to SwiftUIScreen

---

Package.swift
WorkflowSwiftUIExperimental/Tests/SwiftUIScreenTests.swift

Fixed WorkflowSwiftUIExperimental tests not building on Mac

Added WorkflowSwiftUIExperimental to package

---

Workflow/Sources/WorkflowLogger.swift
WorkflowCombine/Sources/Logger.swift
WorkflowConcurrency/Sources/Logger.swift
WorkflowReactiveSwift/Sources/Logger.swift
WorkflowRxSwift/Sources/Logger.swift

the existing os logging implementations log various type descriptions as part of the log message. these strings are apparently calculated even if the logging has been disabled, which introduces unneeded/undesirable work in release builds. these logs shouldn't be made in release builds, and should be opt-in in other contexts.
this change adds short circuiting logic for all the os logging methods in addition to a new environment variable check that can be used to enable the logging when debugging.
~- [x] UI Tests~ n/a
~- [x] Snapshot Tests (iOS only)~ n/a
~- [x] I have made corresponding changes to the documentation~ n/a

[fix]: short circuit worker logging & require explicit opt-in

---

WorkflowRxSwift/Sources/ObservableWorkflow.swift
WorkflowRxSwift/Tests/Rx+ReactiveWorkers.swift

[fix]: update RxSwift bindings to observe on main thread

---

WorkflowSwiftUI/Sources/ObservableScreen.swift
WorkflowSwiftUI/Sources/StateAccessor.swift
WorkflowSwiftUI/Tests/ObservableScreenTests.swift
WorkflowSwiftUIExperimental/Sources/SwiftUIScreen.swift
WorkflowSwiftUIExperimental/Tests/SwiftUIScreenTests.swift

- View environment customizations on hosting VCs now propagate to SwiftUI environment
- ModeledHostingController implementations now conform to ViewEnvironmentObserving
- Added tests
These changes ensure that any view environment customizations made to a Swift UI screen's backing VC are propagated to the SwiftUI environment. We hit this issue in Market when attempting to propagate the VC's navigation item to SwiftUI and there may be other uses for this behaviour too.

[fix] View environment customizations on hosting VCs now propagate to SwiftUI environment

---

WorkflowCombine/Testing/PublisherTesting.swift
WorkflowCombine/Testing/WorkerTesting.swift
WorkflowConcurrency/Testing/WorkerTesting.swift
WorkflowReactiveSwift/Testing/SignalProducerWorkflowTesting.swift
WorkflowReactiveSwift/Testing/WorkerTesting.swift
WorkflowRxSwift/Testing/ObservableTesting.swift
WorkflowRxSwift/Testing/WorkerTesting.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift

This PR updates some comments on testing methods to improve clarity around the expected behavior. It replaces `should` with `will` to make it clearer that the provided renderings/outputs will not be validated against the rendering/output of the workflow/worker, but instead they will be stubbed as the rendering/output for the workflow/worker when called.
It also includes some other minor style changes that were picked up by the linter.

Comment Updates to Improve Clarity

---

Documentation/WorkflowSwiftUI Adoption Guide.md

A documentation follow-up to #283.

WorkflowSwiftUI adoption guide

---

Package.swift
Samples/Project.swift
Samples/Tuist/Config.swift

These weren't being picked up on CI but could fail to build locally. The Tuist option to enforce dependencies should help detect similar stuff in the future.

fix: explicit test dependencies

---

.gitignore
Package.resolved
Package.swift
Samples/Tuist/Package.resolved
WorkflowSwiftUIMacros/Tests/Derived/ObservableStateMacroTests.swift

This PR extends SwiftSyntax support up through 6, and pins our dependencies locally to ensure they're consistent for local dev and in CI.

feat: pin swiftpm dependencies

---

WorkflowConcurrency/Sources/Worker.swift

Changed WorkflowConcurrency Worker task priority to high

---

RELEASING.md

Updating instructions for 2 main reasons:
1. Be explicit about what's needed for consumption via SPM.
2. Add all the steps actually required to publish to CocoaPods to remove guesswork and debugging.

Improve releasing instructions

---

WorkflowSwiftUI/Sources/ActionModel.swift
WorkflowSwiftUI/Sources/StateAccessor.swift
WorkflowSwiftUI/Sources/Store+Preview.swift

Creating a static model is useful for testing, and the missing `public init` on `ActionModel` makes that difficult to do. This PR adds that init along with a couple static factory methods for that use case.

feat: expose helpers for static models

---

.swiftformat

changing the lint preference for this repo from having ACLs on extensions to declarations. this just changes the config – i did not run it against the repo yet.

[gardening]: swiftformat – prefer acl's on declarations

---

Package.resolved
Package.swift
Samples/Project.swift
Samples/Tuist/Package.resolved
WorkflowTesting/Sources/RenderTesterResult.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift

- Before: assertStateModifications was difficult to use because the diffs for failed assertions were difficult to read
- After: Incorporate CustomDump into assertStateModifications to make the assertions easy to read
|Before|After|
|:-:|:-:|
|<img width="643" alt="Screenshot 2024-12-02 at 10 25 14 AM" src="https://github.com/user-attachments/assets/49340800-73f4-4016-9034-9017d39a5b92">|<img width="462" alt="Screenshot 2024-12-02 at 10 23 54 AM" src="https://github.com/user-attachments/assets/ce5fc790-b65b-4bc0-b113-cf4ddaad2ed2">|
|Before|After|
|:-:|:-:|
|<img width="774" alt="image" src="https://github.com/user-attachments/assets/d8ab25ae-5c89-413b-adec-30e81bb99218">|![image](https://github.com/user-attachments/assets/4d970a88-5e86-4307-810c-d748a37c57b0)|

[feat]: adopt swift-custom-dump in some testing utilities

---

WorkflowTesting/Sources/RenderTesterResult.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift

This expands the usage of swift-custom-dump to improve test failure readability

Use swift-custom-dump for all comparisons in RenderTesterResult

---

WorkflowSwiftUI/Sources/ObservableScreen.swift
WorkflowSwiftUI/Tests/PreferredContentSizeTests.swift
WorkflowSwiftUIExperimental/Sources/SwiftUIScreen.swift

This is a possible solution for preferredContentSize of SwiftUI content, for discussion.
A summary of the problem:
- The system provided PCS calculation is unconstrained and not useful to us. We need to calculate this manually.
- SwiftUI ScrollViews greedily fill the space available, but will report the natural content size when given an infinite size.
This solution finds an appropriate PCS for the general case by measuring in a few different constraints and combining the results. This accommodates content with no scroll view, as well as content with scroll views in either axis or both.
~~If we like this I'll follow up with tests that validate PCS in various permutations of size and scrolling axes.~~ tests added!

feat: flexible SwiftUI preferredContentSize calc [UI-7665]

---

WorkflowUI/Sources/Screen/ScreenViewController.swift

The dylib being generated internally is code stripping private vars incorrectly. This should resolve it.
N/A / validated by internal CI

Resolve Bazel dylib issue due to aggressive code stripping

---

Workflow/Sources/SubtreeManager.swift
Workflow/Sources/WorkflowHost.swift
Workflow/Sources/WorkflowLogger.swift
Workflow/Sources/WorkflowNode.swift
Workflow/Tests/PerformanceTests.swift
Workflow/Tests/WorkflowNodeTests.swift

minor cleanup of a now-superfluous parameter used for logging determinations

[gardening]: remove unneeded 'isRootNode' param

---

Samples/AsyncWorker/Sources/AsyncWorkerWorkflow.swift
Tooling/Templates/Workflow (Verbose).xctemplate/Default/___FILEBASENAME___Workflow.swift
Tooling/Templates/Workflow (Verbose).xctemplate/generateWorkerReactiveSwift/___FILEBASENAME___Workflow.swift
Tooling/Templates/Workflow (Verbose).xctemplate/generateWorkerRxSwift/___FILEBASENAME___Workflow.swift
Workflow/Sources/Workflow.swift
Workflow/Tests/AnyWorkflowTests.swift
WorkflowCombine/TestingTests/TestingTests.swift
WorkflowConcurrency/TestingTests/TestingTests.swift
WorkflowReactiveSwift/TestingTests/TestingTests.swift
WorkflowRxSwift/TestingTests/TestingTests.swift

Remove the empty workflowDidChange(from previousWorkflow:state:) method from Xcode project templates and tests.

Remove empty workflowDidChange from Xcode project templates

---

Workflow/Sources/SubtreeManager.swift

small refactor of `ChildKey` to remove custom `Hashable` requirement implementations in favor of synthesized ones

[gardening]: remove unneeded code from ChildKey

---

Workflow/Sources/SubtreeManager.swift
Workflow/Sources/WorkflowHost.swift
Workflow/Sources/WorkflowNode.swift
Workflow/Tests/SubtreeManagerTests.swift
Workflow/Tests/TestUtilities.swift
Workflow/Tests/WorkflowNodeTests.swift

- introduce a `HostContext` type to hold 'host-level' information to be distributed to various entities throughout the workflow tree
- currently it holds the two optional top-level injected properties: 'observers' and the 'debugger'
- in the future i expect this to be useful for propagating additional top-level configuration information downward (e.g. new runtime behavior options), as well as offering a convenient means for communicating back to the 'root' in some circumstances (e.g. recording nodes that changed when applying actions)
note: no new tests added as no new functionality introduced yet

[refactor]: introduce a 'HostContext' for exposing host info through tree

---

Workflow/Sources/SubtreeManager.swift

micro-optimization to merge two dictionary accesses into one

[gardening]: merge two dictionary accesses into one

---

Workflow/Sources/SubtreeManager.swift
WorkflowUI/Sources/ViewControllerDescription/UIViewController+Extensions.swift
WorkflowUI/Sources/ViewControllerDescription/ViewControllerDescription.swift

it was pointed out that `precondition` failure messages are generally not displayed in crash reports, so `fatalError` may be a better tool to handle terminating conditions. this change swaps out usage of `precondition` with `fatalError` for this reason.

[gardening]: swap some preconditions with fatalError for better debugging

---

WorkflowTesting/Sources/RenderTesterResult.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift

updates some testing API to use more defaulted parameters and pass them through to the `expectNoDifference` method from `CustomDump`, as the existing `XCTAssertNoDifference` has been deprecated.

[gardening]: fix some deprecation warnings

---

Workflow/Sources/Debugging.swift
Workflow/Sources/SubtreeManager.swift
Workflow/Sources/WorkflowHost.swift
Workflow/Sources/WorkflowNode.swift
Workflow/Tests/HostContextTests.swift
Workflow/Tests/TestUtilities.swift
Workflow/Tests/WorkflowNodeTests.swift

refactors action propagation to no longer instantiate any `WorkflowDebugInfo` types unless there is a `WorkflowDebugger` set on the host. this should avoid some unnecessary string allocations and reflection metadata lookups.

[perf]: don't instantiate debugger info if not needed

---

Workflow/Sources/SubtreeManager.swift
Workflow/Sources/WorkflowObserver.swift

small changes to:
1. avoid an unnecessary buffer copy during render() when updating event pipes
2. allow our 'session' id generation to wrap so it doesn't need to perform bounds checks (it functionally cannot overflow so they are unneeded)

[perf]: a couple more micro optimizations

---

Samples/TicTacToe/Tests/AuthenticationWorkflowTests.swift
Samples/Tutorial/Tutorial5.md
WorkflowCombine/Testing/WorkerTesting.swift
WorkflowCombine/TestingTests/TestingTests.swift
WorkflowConcurrency/Testing/WorkerTesting.swift
WorkflowConcurrency/TestingTests/TestingTests.swift
WorkflowReactiveSwift/Testing/WorkerTesting.swift
WorkflowReactiveSwift/TestingTests/TestingTests.swift
WorkflowRxSwift/Testing/WorkerTesting.swift
WorkflowRxSwift/TestingTests/TestingTests.swift
WorkflowTesting/Sources/WorkflowRenderTester.swift

When I first saw tests that used this function, I thought it was asserting that the `worker` passed in, matches the `workflow.worker` (which it does do), and that it was asserting that `producingOutput == workflow.worker.output` (which it does NOT do). Instead, neither of the workers are ever run. The `producingOutput` is used as mock output. So renaming these to make it more clear what is going on.

Rename `expect(worker:producingOutput:)` to be more clear about what it is asserting

---

.buildscript/build_swift_docs.sh
Samples/Project.swift
Samples/Tuist/Package.swift
Samples/Tutorial/README.md
Samples/Workspace.swift

Gardening PR. I bounce between several Tuist-generated projects and I regret giving them all generic names. This makes it easier to pick out from Xcode's recent projects list.

build: rename generated project

---

WorkflowSwiftUIExperimental/Sources/SwiftUIScreen.swift

To begin phasing out SwiftUIScreen & WorkflowSwiftUIExperimental in favor of ObservableScreen & WorkflowSwiftUI.

feat: deprecate SwiftUIScreen

---

Documentation/WorkflowSwiftUI Adoption Guide.md

Adding details to the parent dependencies section of the WorkflowSwiftUI Adoption Guide

---

Workflow/Sources/AnyWorkflow.swift
Workflow/Tests/AnyWorkflowTests.swift

Adds a way to map a workflow's `Never` output type to a different type without generating compiler warnings.  Fixes https://github.com/square/workflow-swift/issues/339
I like this solution because the natural inclination is to simply delete the block containing unreachable code and that just works:
```diff
-            .mapOutput { switch $0 {} }
+            .mapOutput()
```
I'm happy to add a test using this but the true validation is to successfully build without warnings.

Adds a convenience for mapping Never outputs to other types

---

Samples/Project.swift
WorkflowSwiftUI/Tests/PreferredContentSizeTests.swift
WorkflowSwiftUI/Tests/XCTestCase+AppHost.swift

Adds an app host to to the WorkflowSwiftUI tests to restore the preferred content size test disabled in #343.
Fixes #346

test: run WorkflowSwiftUI tests in app host

---

Package.swift
WorkflowCombine/Testing/WorkerTesting.swift
WorkflowConcurrency/Testing/WorkerTesting.swift
WorkflowReactiveSwift/Testing/WorkerTesting.swift
WorkflowRxSwift/Testing/WorkerTesting.swift
WorkflowTesting/Sources/Internal/AppliedAction.swift
WorkflowTesting/Sources/Internal/RenderTester+TestContext.swift
WorkflowTesting/Sources/RenderTesterResult.swift
WorkflowTesting/Sources/WorkflowActionTester.swift
WorkflowTesting/Tests/TestingFrameworkCompatibilityTests.swift

migrates test utilities from `XCTest` assertions to analogs provided by the `CustomDump` and `IssueReporting` libraries. this should fix the issue where assertion failures would be invisible to client code written using Swift Testing rather than XCTest.
ideally we should probably add a lint check in the relevant places to enforce use of the appropriate API, but that will be a separate task.
resolves: https://github.com/square/workflow-swift/issues/330

[chore]: improve Swift Testing support in test utilities

---

WorkflowSwiftUI/Sources/ObservableScreen.swift
WorkflowSwiftUI/Sources/UIViewController+Orientation.swift
WorkflowSwiftUI/Tests/ObservableScreenTests.swift

Adds a bunch of optional methods to the `ObservableScreen` protocol to customize view controller behavior:
- preferredStatusBarStyle
- prefersStatusBarHidden
- preferredStatusBarUpdateAnimation
- supportedInterfaceOrientations
- preferredScreenEdgesDeferringSystemGestures
- prefersHomeIndicatorAutoHidden
- pressesBegan
- accessibilityPerformEscape

feat: ObservableScreen view controller preferences

---

Package.swift

- bumped mac catalyst min version to 16 to fix downstream build issues
- going to treat this as a 'hotfix' followup to the 4.0.0 tag

[fix]: bump catalyst to fix build

---

WorkflowConcurrency/Sources/AsyncSequenceWorker.swift

Added catch for errors in AsyncSequenceWorker.

AsyncSequenceWorker’s should not throw errors

---

ViewEnvironment/Sources/EnvironmentValues+ViewEnvironment.swift

Restores the ability to bridge ViewEnvironment back out, which was removed in #319.
This PR does it with SPI currently, but tbh I think we could safely revert the deprecation and be OK.

feat: allow SwiftUI ViewEnvironment access via SPI

---

Workflow/Sources/RuntimeConfiguration.swift
Workflow/Sources/WorkflowHost.swift
Workflow/Tests/RuntimeConfigTests.swift
Workflow/Tests/TestUtilities.swift
Workflow/Tests/WorkflowHostTests.swift

introduces the notion of a 'runtime configuration' in order to support opting into new behaviors to the Workflow runtime over time. currently this is behind an SPI, and should be considered experimental and exempt from semantic versioning standards.

[feat]: introduce runtime configuration SPI

---

WorkflowUI/Sources/ViewControllerDescription/ViewControllerDescription.swift
WorkflowUI/Tests/ViewControllerDescriptionTests.swift

This PR adds support to `ViewControllerDescription` for dynamic view controller types. This is used in cases where the static type of the description's view controller is not granular enough, like implementations that supply a `UIViewController.self` type to `ViewControllerDescription` instead of the subclass type.
This is behind a `DynamicControllerTypes` SPI to encourage use of the existing initializer that uses generics.

feat: Adding support for dynamic view controller types
