square/workflow-swift

.github/workflows/release.yml
.github/workflows/swift.yaml
RELEASING.md

Rename trunk branch to main

---

.github/workflows/swift.yaml

Run WorkflowTestingTests

---

WorkflowUI/Sources/Container/ContainerViewController.swift

Swap generic parameters in ContainerViewController

---

WorkflowReactiveSwift/Sources/Logger.swift
WorkflowReactiveSwift/Sources/Worker.swift
WorkflowUI/Tests/ContainerViewControllerTests.swift

Follow-up from #12, we had dropped the logging there, adding it back in here.

Add os_log logging to Workers

---

WorkflowReactiveSwift/Sources/SignalProducerWorkflow.swift
WorkflowReactiveSwift/Sources/SignalWorker.swift
WorkflowReactiveSwift/Tests/SignalTests.swift
WorkflowUI/Tests/ContainerViewControllerTests.swift

* Deprecating `SignalWorker`
* Making `Signal` `AnyWorkflowConvertible`

Make Signal AnyWorkflowConvertible

---

Samples/Tutorial/Tutorial5.md

Fix two typos in Tutorial5.md

---

CHANGELOG.md

Anything else we should call out here?

Changelog v1.0.0.alpha.1

---

WorkflowReactiveSwiftTesting.podspec
WorkflowTesting.podspec
WorkflowTesting/Tests/WorkflowActionTesterTests.swift
WorkflowTesting/Tests/WorkflowRenderTesterDeprecatedTests.swift
WorkflowTesting/Tests/WorkflowRenderTesterFailureTests.swift
WorkflowTesting/Tests/WorkflowRenderTesterTests.swift
WorkflowUI.podspec

Removing unncessary dependencies

---

MigrationGuide_v1.0.md
WorkflowReactiveSwift/Sources/SignalWorker.swift

Remove deprecated SignalWorker APIs

---

Workflow/Sources/Workflow.swift

Fixes #68. This function is no longer public.

Update `Workflow.render` documentation

---

Samples/Tutorial/README.md

Minor edits to the main tutorial README. Additional changes/fixes to the tutorials themselves will follow.

Update tutorial README

---

Package.swift
Samples/AlertContainer/AlertContainer.podspec
Samples/BackStackContainer/BackStackContainer.podspec
Samples/ModalContainer/ModalContainer.podspec
Samples/SplitScreenContainer/SplitScreenContainer.podspec
Workflow.podspec
Workflow/Sources/SubtreeManager.swift
WorkflowReactiveSwift.podspec
WorkflowReactiveSwiftTesting.podspec
WorkflowRxSwift.podspec
WorkflowRxSwiftTesting.podspec
WorkflowTesting.podspec
WorkflowUI.podspec

Bump the deployment target to iOS 11 / macOS High Sierra

---

Samples/Tutorial/Tutorial1.md
Tooling/Templates/Screen (View Controller).xctemplate/___FILEBASENAME___Screen.swift
Tooling/Templates/Workflow (Verbose).xctemplate/___FILEBASENAME___Workflow.swift

Update Tutorial 1

---

Samples/Tutorial/Frameworks/Tutorial1Complete/Sources/Welcome/WelcomeScreen.swift
Samples/Tutorial/Tutorial1.md

Let's ensure there is consistency between what the tutorial is telling you to do and the "done" version. 😉

Update finished Tutorial 1 to match docs

---

Samples/Tutorial/Frameworks/Tutorial1Complete/Sources/Welcome/WelcomeScreen.swift
Samples/Tutorial/Tutorial1.md
Tooling/Templates/Workflow (Verbose).xctemplate/___FILEBASENAME___Workflow.swift

This came up in #76. I updated the tutorial and finished code to defer creation of the view until it's needed.

Tutorial 1: Defer creation of the WelcomeView until it's needed

---

Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/RootWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/Todo/List/TodoListScreen.swift
Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/Todo/List/TodoListWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/Welcome/WelcomeScreen.swift
Samples/Tutorial/Frameworks/Tutorial2Complete/Sources/Welcome/WelcomeWorkflow.swift
Samples/Tutorial/Tutorial2.md

Update Tutorial 2

---

Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/RootWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/Edit/TodoEditScreen.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/Edit/TodoEditWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/List/TodoListScreen.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Todo/List/TodoListWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Welcome/WelcomeScreen.swift
Samples/Tutorial/Frameworks/Tutorial3Complete/Sources/Welcome/WelcomeWorkflow.swift
Samples/Tutorial/Tutorial3.md

Update Tutorial 3

---

Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/RootWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/Edit/TodoEditWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/List/TodoListWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Todo/TodoWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial4Complete/Sources/Welcome/WelcomeWorkflow.swift
Samples/Tutorial/Tutorial4.md

Update Tutorial 4

---

Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/RootWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/Edit/TodoEditScreen.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/Edit/TodoEditWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/List/TodoListScreen.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/List/TodoListWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Todo/TodoWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Welcome/WelcomeScreen.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Sources/Welcome/WelcomeWorkflow.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/RootWorkflowTests.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/TodoEditWorkflowTests.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/TodoListWorkflowTests.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/TodoWorkflowTests.swift
Samples/Tutorial/Frameworks/Tutorial5Complete/Tests/WelcomeWorkflowTests.swift
Samples/Tutorial/Frameworks/TutorialBase/TutorialBase.podspec
Samples/Tutorial/Tutorial2.md
Samples/Tutorial/Tutorial3.md
Samples/Tutorial/Tutorial4.md
Samples/Tutorial/Tutorial5.md

Update Tutorial 5 (testing)

---

Package.swift

Add WorkflowSwiftUI to Package.swift

---

Workflow.podspec
WorkflowReactiveSwift.podspec

Bump ReactiveSwift to 7.0.0

---

WorkflowRxSwift.podspec

Bump RxSwift to 6.5

---

RELEASING.md

Added WorkflowCombine and WorkflowCombineTesting to releasing doc

---

version.rb

[release]: bump version to 2.3.0

---

.github/CODEOWNERS

Add UI Systems to WorkflowUI Codeowners

---

version.rb

Updated version number for a new release

---

version.rb

[release]: bump version to 2.5.0

---

Samples/Tutorial/Tutorial1.md

Add missing keyword 'func' to Tutorial1.md

---

version.rb

[release]: bump version to 3.0.0

---

WorkflowUI/Sources/Observation/WorkflowUIEvents.swift
WorkflowUI/Sources/Observation/WorkflowUIViewController.swift
WorkflowUI/Tests/WorkflowUIViewControllerTests.swift

Add ViewWillDisappear / ViewDidDisappear to WorkflowUI experimental observation

---

version.rb

[release]: bump version to 3.1.0

---

version.rb

[release]: bump version to 3.3.0

---

.github/CODEOWNERS

- make more UI-related code have shared ownership with @square/ui-systems-ios
sanity-checked the wildcard logic [here](https://github.com/square/workflow-swift/pull/268)

[chore]: update codeowners

---

Samples/Tutorial/Tutorial.xcodeproj/project.pbxproj

Changed Tutorial deployment target to iOS 15 to fix build issue

Changed Tutorial deployment target

---

WorkflowSwiftUIExperimental.podspec

Bump WorkflowSwiftUIExperimental to 0.4

---

RELEASING.md

Added WorkflowSwiftUIExperimental to lib lint

---

WorkflowSwiftUIExperimental/Sources/SwiftUIScreen.swift

Follow up to [this thread of comments on a previous PR](https://github.com/square/workflow-swift/pull/277#discussion_r1541943323).

[chore]: add comment describing SwiftUIScreen's background color override

---

Package.swift

Bumps package file to 5.9 swift tools

Adds targeted strict concurrency setting to package file

---

Package.swift

Updated swift-syntax package URL

---

Package.swift
Samples/Tuist/ProjectDescriptionHelpers/Project+Workflow.swift

feat: bump minimum to iOS 16

---

Tooling/Templates/Workflow (Verbose).xctemplate/Default/___FILEBASENAME___Workflow.swift

Fix workflow template missing parentheses

---

.github/workflows/docs.yaml
.github/workflows/swift.yaml

might resolve: https://github.com/square/workflow-swift/security/code-scanning/12

[chore]: add permissions to github workflows per recommendation
